//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestParsing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBParsingEntities1 : DbContext
    {
        public DBParsingEntities1()
            : base("name=DBParsingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Resume> Resume { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<Spec> Spec { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
